---
- name: Install packages for app server
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name: ["git", "ruby-full" ,"ruby-bundler" ,"build-essential"  ]
