---
- name: Configure MongoDB
  hosts: dbs
  become: true
  vars:
      pb_mongo_bind_ip: 0.0.0.0

  roles:
      - name: db
        vars:
            db_mongo_bind_ip: "{{ pb_mongo_bind_ip }}"
