---
- name: Deploy App
  hosts: apps
  become: true
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Fetch the latest version of application code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart redditApp

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: Start Reddit App
      become: true
      ansible.builtin.systemd:
        name: reddit-app.service
        state: started
        enabled: true

  handlers:
    - name: restart redditApp
      become: true
      ansible.builtin.systemd: name=puma state=restarted
