---
# tasks file for app
- name: Install packages
  apt:
    name: ["git", "ruby-full" ,"ruby-bundler" ,"build-essential"  ]

- name: Add unit file for Reddit-app
  copy:
    src: reddit-app.service
    dest: /etc/systemd/system/reddit-app.service
  notify: reload reddit-app

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/ubuntu/db_config
    owner: ubuntu
    group: ubuntu

- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
