---
- name: Deploy App
  hosts: apps
  become: true
  tasks:
    - name: install git
      apt:
        name: git
        state: present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart redditApp

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: Start Puma
      become: true
      systemd:
        name: puma
        state: started
        enabled: yes

  handlers:
    - name: restart redditApp
      become: true
      systemd: name=puma state=restarted
