---
galaxy_info:
  role_name: linux_administration
  namespace: glennbell
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "yamllint"
platforms:
- name: instance
  box: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
